/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_979636_3.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_979636_1[] = { "ShoulderPress", "curl", "idle", "lateralraise" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_979636_2_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_979636_2_axes_size = 6;
ei_dsp_config_spectral_analysis_t ei_dsp_config_979636_2 = {
    2, // uint32_t blockId
    4, // int implementationVersion
    6, // int length of axes
    0.00218401048122f, // float scale-axes
    3, // int input-decimation-ratio
    "low", // select filter-type
    2.63671875f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    32, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    false, // boolean do-fft-overlap
    1, // int wavelet-level
    "rbio3.3", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_979636_2[60] = { 0.008908300099930927, -0.05640177939306287, -0.8191953548029357, 2.166226018176359, 3.53602703381695, -3.704125364153993, -3.650185999215818, -4.217304697223738, -4.424997748580633, -4.786483112036013, 0.0027214338743885725, 0.3224628090169098, -0.6605817866091634, 2.096137706906188, 3.3188757942437066, -4.934478048249787, -4.934593751383763, -5.1547116317001045, -5.226616995942359, -5.940213257658716, 0.005450624308272666, -0.2160881653743084, -0.8934612558241568, 2.3552505712883147, 4.445832182028714, -4.336162663441078, -4.326800312715418, -4.687106839348288, -4.837473567326864, -5.551546330545463, 0.061618810290397674, 0.06805880659570297, -0.45492272620755886, 2.022407243532293, 2.9769019181712295, -2.4504055074616975, -2.2605938619258357, -2.4744707172992184, -2.644169588182487, -3.050072368453531, 0.14985329307451406, -0.10603381503857306, -1.09331346074594, 2.3862054432139677, 4.338131663027932, -1.4251185386788612, -1.307552944094527, -2.103583229055592, -2.434799682860281, -2.642037727318558, 0.059247934602328814, -0.09539504623378389, -0.7250445800431657, 2.2325609321687736, 3.766339933813787, -2.266506479768192, -2.1430356848473644, -2.662117891218148, -2.985918175005445, -3.28026432056053 };
const float ei_dn_standard_scaler_scale_979636_2[60] = { 657.114917809765, 1.2719882790313086, 2.096252623556, 2.0475397366783996, 0.43039340767291745, 3.6134806246665514, 4.366337016196386, 2.1941578092373013, 2.206936159888585, 2.884002976074043, 881.9734835148741, 1.5161426690525068, 1.4491136132679758, 2.4279857696000686, 0.5074552405261876, 1.6401212257840194, 1.7780865150396725, 1.704451796025508, 1.6969717344486301, 1.5772177925425157, 432.8063012976543, 1.9187439683238627, 1.8776555080715058, 2.9744095320033366, 0.5553019426845367, 1.337122749650089, 1.374072677763993, 1.4261706137671146, 1.4105609630878742, 1.3437635720864778, 27.257680041619142, 1.3227341165379893, 1.066906566955215, 2.3408643754012184, 0.5328385914365835, 1.334858268273561, 1.3779302779549807, 1.4729522036190534, 1.5984462179789032, 1.4170532557145572, 14.522109745988194, 2.018001850505424, 1.8676748829162106, 3.6261287844514323, 0.6481111306224241, 1.1774072072855617, 1.2606600452048315, 1.1648396733585538, 1.3171694104017897, 1.1333335055559957, 34.51330644396898, 1.4618184765398, 1.132434783639937, 2.643598071493563, 0.5580264638192691, 1.489136870389396, 1.4843186739950722, 1.47256532648236, 1.5636867796848328, 1.3988757899394642 };
const float ei_dn_standard_scaler_var_979636_2[60] = { 0.000002315886903148868, 0.6180644737221043, 0.22756882214793514, 0.23852577864333516, 5.398446213872452, 0.07658585042541097, 0.05245241546777891, 0.20771328788543544, 0.2053148958014117, 0.12022882190799322, 0.0000012855499133537903, 0.43503065316428463, 0.4762062898315792, 0.1696319779016286, 3.883331953130145, 0.37174753869277716, 0.3162963814220901, 0.34421560350801145, 0.34725681918790363, 0.4019913097617948, 0.000005338421363004864, 0.27162262676782506, 0.2836404520346677, 0.1130312346851524, 3.2429601673619746, 0.5593162589877939, 0.5296397741925734, 0.49165112002402456, 0.5025928184043646, 0.5538016847977656, 0.0013459292186534463, 0.5715508692532858, 0.8785110398399193, 0.18249353984108507, 3.522156563191338, 0.5612155401214448, 0.5266784073062243, 0.4609169623517053, 0.3913847892109094, 0.4979980653240539, 0.004741770943385951, 0.24555957875726336, 0.2866800314300543, 0.07605250991789801, 2.3806800898923757, 0.7213509699928325, 0.629222179305912, 0.7370003468085169, 0.5763903850103993, 0.7785464761850793, 0.0008395119159790672, 0.4679647131632623, 0.779782705303626, 0.14308995504626362, 3.2113704678398673, 0.45095246642736975, 0.4538848610344735, 0.4611591813631313, 0.4089784938294623, 0.5110244647485103 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_979636_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_979636_2,
    .mean_data_len = 60,
    .scale_data = (float *)ei_dn_standard_scaler_scale_979636_2,
    .scale_data_len = 60,
    .var_data = (float *)ei_dn_standard_scaler_var_979636_2,
    .var_data_len = 60
};
ei_data_normalization_t ei_data_normalization_config_979636_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_979636_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_979636_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_979636_1[ei_dsp_blocks_979636_1_size] = {
    { // DSP block 2
        2,
        60, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_979636_2, // pointer to config struct
        ei_dsp_config_979636_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_979636_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_979636_2, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_979636_3 = {
    .implementation_version = 1,
    .model = tflite_learn_979636_3,
    .model_size = tflite_learn_979636_3_len,
    .arena_size = tflite_learn_979636_3_arena_size
};

const uint8_t ei_output_tensors_indices_979636_3[1] = { 0 };
const uint8_t ei_output_tensors_size_979636_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_979636_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_979636_3,
    .output_tensors_size = ei_output_tensors_size_979636_3,
    .quantized = 1,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_979636_3,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_979636_4 = {
    .implementation_version = 1,
    .block_id = 4,
    .anom_axis = ei_classifier_anom_axes_979636_4,
    .anom_axes_size = 6,
    .anom_clusters = ei_classifier_anom_clusters_979636_4,
    .anom_cluster_count = 32,
    .anom_scale = ei_classifier_anom_scale_979636_4,
    .anom_mean = ei_classifier_anom_mean_979636_4,
};

const uint8_t ei_learning_blocks_979636_1_size = 2;
const uint32_t ei_learning_block_979636_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_979636_3_inputs_size = 1;
const uint32_t ei_learning_block_979636_4_inputs[1] = { 2 };
const uint8_t ei_learning_block_979636_4_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_979636_1[ei_learning_blocks_979636_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_979636_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_979636_3_inputs,
        ei_learning_block_979636_3_inputs_size,
    },
    {
        4,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_979636_4,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_979636_4_inputs,
        ei_learning_block_979636_4_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_979636_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_979636_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_979636_1[ei_postprocessing_blocks_979636_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_979636_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_979636_1_size = 0;

uint32_t *freeform_outputs_979636_1 = nullptr;

const ei_impulse_t impulse_979636_1 = {
    .project_id = 979636,
    .project_owner = "Erlind",
    .project_name = "Erlind-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 5,

    .nn_input_frame_size = 60,
    .raw_sample_count = 50,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 50 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_979636_1_size,
    .dsp_blocks = ei_dsp_blocks_979636_1,

    .learning_blocks_size = ei_learning_blocks_979636_1_size,
    .learning_blocks = ei_learning_blocks_979636_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_979636_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_979636_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "accelX + accelY + accelZ + gyroX + gyroY + gyroZ",
    .slice_size = (50/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_979636_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_979636_1_size,
    .freeform_outputs = freeform_outputs_979636_1
};

ei_impulse_handle_t impulse_handle_979636_1 = ei_impulse_handle_t( &impulse_979636_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_979636_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_979636_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_979636_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_979636_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
